Update Fix  MIUI-OOS.yml

diff --git a/.github/workflows/MIUI-OOS.yml b/.github/workflows/MIUI-OOS.yml
--- a/.github/workflows/MIUI-OOS.yml
+++ b/.github/workflows/MIUI-OOS.yml
@@ -35,19 +35,27 @@ jobs:
       run: |
             sed -i 's/qcom,mdss-pan-physical-width-dimension = <69>;$/qcom,mdss-pan-physical-width-dimension = <695>;/' arch/arm64/boot/dts/qcom/dsi-panel-k6-38-0c-0a-fhd-dsc-video.dtsi
             sed -i 's/qcom,mdss-pan-physical-height-dimension = <154>;$/qcom,mdss-pan-physical-height-dimension = <1546>;/' arch/arm64/boot/dts/qcom/dsi-panel-k6-38-0c-0a-fhd-dsc-video.dtsi
+            
+    - name: Debug Path & Confirm DTS exists
+      run: |
+        echo "Checking DTS path..."
+        ls arch/arm64/boot/dts/qcom || (echo "❌ DTS not found!" && exit 1)
 
     - name: Build
       run: |
             export ARCH=arm64
+            export SUBARCH=arm64
             export PATH="${PWD}/clang/bin:${PWD}/gcc64/bin:${PWD}/gcc32/bin:${PATH}"
             export KBUILD_BUILD_USER=runner
             export KBUILD_BUILD_HOST=slipzsix
-            export KBUILD_COMPILER_STRING="${PWD}/clang"
+            export KBUILD_COMPILER_STRING="$(${PWD}/clang/bin/clang --version | head -n 1)"
             export LLVM=1 
             export LLVM_IAS=1
             export CLANG_TRIPLE=aarch64-linux-gnu-
             export CROSS_COMPILE=aarch64-linux-android-
             export CROSS_COMPILE_ARM32=arm-linux-androideabi-
+            export HOSTCC=clang
+            export HOSTLD=ld.lld
             make O=out clean
             make O=out mrproper
             make O=out ARCH=arm64 sweet_defconfig
